
server:
  port: 8888
  
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
      
spring:
  application:
    name: FLATTENPDF-CONFIG-SERVER
    
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BabaDharubai/Templates

  
    

